name: Test workflow
on: push
jobs:
  job1:
    name: jb1
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: v22.22.0
      - run: node -v
      - run: npm -v
          

